### ISSUE TITLE
Error loading `lego-sales` Shiny App

### ISSUE THREAD

**Issue by luciorq** [mine-cetinkaya-rundel/teach-r-online#1]
Hello @mine-cetinkaya-rundel ,

I'm just reporting that I couldn't load [`lego-sales` Shiny App](https://gallery.shinyapps.io/lego-sales/) used on [*building interactive tutorials in R*](https://mine-cetinkaya-rundel.github.io/teach-r-online/02-tutorial/02-tutorial.html).

It is reporting an error, as seen on the following screenshot, taken on October 24th, 2020.

<https://gallery.shinyapps.io/lego-sales/>

![image](https://user-images.githubusercontent.com/22479186/97091195-80230a80-1610-11eb-9271-a8509f463a35.png)

Thanks for the amazing effort on this content.

**Comment by luciorq** [comment]
Linked to rstudio-education/instructor-training#2

**Comment by mine-cetinkaya-rundel** [comment]
This should be fixed now, thanks for reporting.
